'use strict'

const readline = require( 'readline' );

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const dictionary = {
'American Standard Code for Information Integracy':
	'Американський стандартний код інформаційної інтеграції',
'Coming right up!': 'Зараз буде!',
'Don\'t mention it': 'Не зважайте на це',
'Everything worked out': 'Все вдалося',
'Global Positioning System': 'Глобальна система розташування',
'Help yourself to': 'Пригощайтесь',
'Here you are': 'Ось, тримай',
'I didn\'t quite catch that': 'Я не зовсім зрозумів',
'I don\'t quite follow you': 'Я не зовсім за вами встигаю',
'I wanted the ground to swallow me up': 'Я хотів провалитися під землю',
'It isn\'t rocket science': 'Це не складно',
'Nice to put a face to the name': 'Приємно познайомитись особисто',
'Not at all': 'Немає за що',
'Practice makes perfect': 'практика створює ідеал',
'Thanks for having me!': 'Дякую за гостинність!',
'You\'re welcome': 'Будь ласка',
'a counterpart': 'колега',
'a slip of a tongue': 'обмовка',
'a syllable': 'склад',
'an integrated circuit': 'інтегральна схема',
'arithmetic logic unit': 'арифметично-логічний пристрій',
'artificial enviroment': 'штучне середовище',
'assistive technology': 'допоміжна технологія',
'astonished': 'приголомшений',
'basic input/output system': 'базова система вводу/виводу',
'be patient with': 'будь обережним з',
'be qualified for': 'бути кваліфікованим у',
'beyond the limits': 'поза межами',
'bus width': 'ширина каналу',
'capacity': 'ємність',
'central processing unit': 'центральний процесор',
'clarification': 'роз\'яснення',
'cold-hearted': 'жорстокий',
'computer addiction': 'комп\'ютерна залежність',
'dual in-line memory modules': 'подвійні вбудовані модулі пам\'яті',
'electronic waste': 'електронне сміття',
'excessive use': 'надмірне використання',
'exhausted': 'виснажений',
'expansion slots': 'слоти розширення',
'extension': 'розширення',
'ferocious animal': 'люта тварина',
'frustrated': 'розчарований',
'gullible': 'легковірний',
'hardware': 'апаратне забезпечення',
'head-mounted display': 'шолом віртуальної реальності',
'hospitality': 'гостинність',
'in particular': 'зокрема',
'inappropriate use': 'неналежне використання',
'input device': 'пристрій вводу',
'interest': 'цікавість',
'let alone': 'не кажучи про',
'loss of privacy': 'брак приватності',
'mainframe computer': 'ЕОМ',
'moody': 'похмурий',
'motherboard': 'материнська плата',
'narrow-minded': 'вузьколобий',
'new gauge': 'новий калібр',
'non-volatile': 'нелеткий',
'obsessed': 'одержимий',
'output device': 'пристрій виводу',
'payroll': 'платіжна відомість',
'peripherals': 'периферійні пристрої',
'permanent': 'постійний',
'personnel department': 'відділ персоналу',
'publicity': 'публічність',
'quick-tempered': 'запальний',
'random access memory': 'оперативна пам\'ять',
'range of colours': 'спектр кольорів',
'read only memory': 'постійна пам\'ять',
'repair and maintance': 'ремонт та обслуговування',
'self-conscious': 'самовпевнений',
'sharp image': 'чітке зображення',
'soft-spoken': 'з тихим голосом',
'software': 'програмне забезпечення',
'stocks': 'акції',
'storage devices': 'накопичувальні пристрої',
'technical specifications': 'технічні характеристики',
'technological dependence': 'технологічна залежність',
'temporary': 'тимчасовий',
'the clock speed': 'швидкість годинника',
'the control unit': 'контрольний пристрій',
'the registers': 'реєстри',
'thick-skinned': 'терплячий',
'to apply for a job': 'подати заявку на роботу',
'to be a bit green': 'бути новачком',
'to be a pain in the neck': 'бути надокучливим',
'to be as hard as nails': 'бути рішучим',
'to be behind the times': 'бути старомодним',
'to be down': 'перестати працювати',
'to be founded by': 'бути заснованим',
'to be notorious for': 'бути горезвісним через',
'to be out and about': 'бути активним',
'to be under the weather': 'бути хворим',
'to clarify': 'роз\'яснювати',
'to commit a crime': 'вчинити злочин',
'to contribute': 'робити внесок',
'to convey meaning/thoughts': 'передати сенс / думки',
'to coordinate the activities': 'координувати діяльність',
'to cut down on': 'зекономити на',
'to execute program instructions': 'виконувати програмні інструкції',
'to expand': 'розширювати',
'to fill out': 'заповнити',
'to get aquanted with': 'познайомитись з',
'to handle demanding applications': 'обробляти вимоги додатків',
'to have a heart of gold': 'бути добрим',
'to have a negative perception': 'мати негативне сприйняття',
'to have an early start': 'рано встати',
'to have experience in': 'мати досвід у',
'to hold a position': 'обіймати посаду',
'to interact with': 'взаємодіяти з',
'to interpret instructions': 'інтерпретувати інструкції',
'to keep track of': 'стежити за',
'to live on': 'жити на',
'to make a chit-chat': 'мати коротку розмову',
'to make a profit': 'отримати прибуток',
'to make an appointment': 'назначити зустріч',
'to marvel out': 'милуватися',
'to measure': 'вимірювати',
'to not take no for an answer': 'не приймати відмов',
'to obey': 'підкорятися',
'to process the data': 'обробляти дані',
'to pronounce': 'вимовляти',
'to put some money by': 'відкласти трохи грошей',
'to raise awareness': 'підвищувати рівень обізнаності',
'to retire from a job': 'звільнитись з роботи',
'to return the favour': 'повернути послугу',
'to run a business': 'вести бізнес',
'to run out of money': 'вичерпати запас грошей',
'to solve a problem': 'розв\'язати проблему',
'to speak one\'s mind': 'висловити чиїсь думки',
'to specialze in': 'спеціалізуватись на',
'to stand for': 'означати',
'to take out a loan': 'взяти позику',
'to work under pressure': 'працювати під тиском',
'to work unsociable hours': 'працювати в неробочий час',
'unauthorized use': 'неавторизоване використання',
'wireless network': 'бездротова мережа',
};
	
const pickRandomKey = obj => {
	const keys = Object.keys( obj );
	return keys[ keys.length * Math.random() << 0 ]
};

const askTranslation = dict => {
	const rightWord = pickRandomKey( dict );
	console.log( dict[ rightWord ] );
	rl.question('Translate into English: ', answer => {
		if ( answer.toUpperCase() === rightWord.toUpperCase() ) {
			console.log('Right!')
		} else {
			console.log(`Incorrect! \n Correct answer is: '${rightWord}'`)
		}
		return  askTranslation( dict );
	});
};

askTranslation( dictionary );
