exports.dictionary = {
'be extendable to' : 'бути розширюваним до',
'the storage capacity' : 'ємність накопичення',
'instantly' : 'миттєво',
'Internet capabilities' : 'можливості інтернету',
'flat battery' : 'батарея з низьким зарядом',
'dead battery' : 'повністю розряджена батарея',
'power-hungry' : 'енергозатратний',
'a power cut' : 'відключення світла',
'to cost the earth' : 'бути неймовірно дорогим',
'to be pricey' : 'бути дорогим',
'to be overcharged' : 'бути надмірно зарядженим',
'to recharge the battery' : 'перезарядити батарею',
'It is a good value for money' : 'це коштує своїх грошей',
'a bargain' : 'угода',
'to make a big difference' : 'все змінювати',
'troubleshooting' : 'вирішення проблем',
'to be scratched' : 'бути подряпаним',
'to be cracked' : 'бути тріснутим',
'to be smashed' : 'бути роздавленим',
'to be torn' : 'бути розірваним',
'to be crumpled' : 'бути пом\'ятим',
'to be stained' : 'бути заплямованим',
'to be chipped' : 'бути розщепленим',
'to be dented' : 'бути вм\'ятим',
'to be burnt' : 'бути спаленим',
'to be bent' : 'бути зігнутим',
'a postponement' : 'відкладення',
'to postpone' : 'відкласти',
'a cancellation' : 'вихід, відміна',
'to cancel' : 'виходити, відміняти',
'cursor control keys' : 'клавіші для контролю курсору',
'dedicated keys' : 'виділені клавіші',
'arrow keys' : 'клавіші зі стрілками',
'insertion' : 'вставка',
'to issue commands' : 'випускати команди',
'to produce a blank space' : 'створювати пробіл',
'to confirm commands' : 'підтвердити команди',
'to select text' : 'виділяти текст',
'to tabulate' : 'табулювати',
'a bar code reader' : 'читач штрих-коду',
'editing keys' : 'функціональні клавіші',
'space bar' : 'клавіша пробіл',
'wired play' : 'дротова гра',
'forwards and backwards' : 'вперед і назад',
'upper case characters' : 'великі літери',
'to drag the image' : 'перетягнути зображення',
'to highlight text' : 'підсвічувати текст',
'to compile a computer program' : 'компілювати комп. програму',
'a brewery' : 'пивоварня',
'to be completely destroyed' : 'бути повністю розбитим',
'to be offensive' : 'бути образливим',
'to offend' : 'ображати',
'descent' : 'походження',
'chief executive officer' : 'виконавчий директор',
'to create intimacy' : 'створювати інтимність',
'a dispenser' : 'дозатор',
'to hit the road' : 'вирушити в дорогу',
'to have a blast' : 'отримати задоволення',
'to come rain or shine' : 'прийти в будь-яку погоду',
'the highlight of the year' : 'головна подія року',
'a selicon chip' : 'кремнієвий чіп',
'to capture an image' : 'захопити зображення',
'a flat-bed scanner' : 'сканер-планшет',
'beneath' : 'внизу(нижче)',
'a slade scanner' : 'телерадіодатчик, сканер для діапазонів',
'a handheld scanner' : 'портативний сканер',
'to get crisp scans' : 'отримати чіткі скани',
'sharpness' : 'різкість(чіткість)',
'colour definition' : 'визначення кольору',
'playback' : 'відьворення',
'blurry picture' : 'розмитий малюнок',
};